package com.exchange.manager.exchangemanager.exception.enums;

public enum FriendlyMessageCodes implements IFriendlyMessageCode {
    OK(1000),
    ERROR(1001),
    SUCCESS(1002),

    USER_NOT_CREATED_EXCEPTION(1500),
    USER_SUCCESSFULLY_CREATED(1501),

    WALLET_ACCOUNT_CREATED_EXCEPTION(1502),
    WALLET_ACCOUNT_SUCCESSFULLY_CREATED(1503),
    WALLET_ACCOUNT_NOT_FOUND_EXCEPTION(1504),

    WALLET_ACCOUNT_SUCCESSFULLY_UPDATED(1505),
    WALLET_ACCOUNT_NOT_ENOUGH_MONEY_EXCEPTION(1506),


    TRANSACTION_NOT_CREATED_EXCEPTION(1507),
    TRANSACTION_SUCCESSFULLY_CREATED(1508),
    TRANSACTION_NOT_FOUND_EXCEPTION(1509),
    USER_SUCCESSFULLY_UPDATED(1510),

    CURRENCY_EXCHANGE_RATE_VALIDATE_EXCEPTION(1511),
    USER_NOT_AUTHENTICATION_EXCEPTION(1512),
    USER_NOT_FOUND_EXCEPTION(1513),
    WALLET_ACCOUNT_AMOUNT_NOT_VALIDATE_EXCEPTION(1514),
    CURRENT_EXCHANGE_RATE_INFORMATION_RETRIEVE(1515),
    WALLET_TRANSACTION_INFORMATION_RETRIEVE(1516);
    ;

    private final int value;

    FriendlyMessageCodes(int value) {
        this.value = value;
    }

    @Override
    public int getFriendlyMessageCode() {
        return value;
    }
}
